
export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  EMPLOYEE: 'EMPLOYEE',
}


export const EXPENSE_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  IN_REVIEW: 'IN_REVIEW',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  REVISED: 'REVISED',
}

export const APPROVAL_ACTION = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ESCALATED: 'ESCALATED',
}

export const CONDITIONAL_RULE = {
  NONE: 'NONE',
  PERCENTAGE: 'PERCENTAGE',
  SPECIFIC: 'SPECIFIC',
  HYBRID: 'HYBRID',
}

export const NOTIFICATION_TYPE = {
  EXPENSE_SUBMITTED: 'EXPENSE_SUBMITTED',
  APPROVAL_REQUESTED: 'APPROVAL_REQUESTED',
  EXPENSE_APPROVED: 'EXPENSE_APPROVED',
  EXPENSE_REJECTED: 'EXPENSE_REJECTED',
  EXPENSE_REVISED: 'EXPENSE_REVISED',
  STEP_COMPLETED: 'STEP_COMPLETED',
  ADMIN_OVERRIDE: 'ADMIN_OVERRIDE',
}

export const OCR_STATUS = {
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
}

export const AUTH = {
  ACCESS_TOKEN_EXPIRY: '15m',
  REFRESH_TOKEN_EXPIRY: '7d',
  BCRYPT_ROUNDS: 12,
  REFRESH_TOKEN_COOKIE: 'refresh_token',
  COOKIE_MAX_AGE_MS: 7 * 24 * 60 * 60 * 1000,
}

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
}

export const CURRENCY = {
  EXCHANGE_RATE_CACHE_TTL_MS: 60 * 60 * 1000,
  FALLBACK_CURRENCY_CODE: 'USD',
  FALLBACK_CURRENCY_SYMBOL: '$',
}

export const AUDIT_ACTION = {
  COMPANY_CREATED: 'COMPANY_CREATED',
  USER_CREATED: 'USER_CREATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  MANAGER_ASSIGNED: 'MANAGER_ASSIGNED',
  POLICY_CREATED: 'POLICY_CREATED',
  POLICY_UPDATED: 'POLICY_UPDATED',
  POLICY_DELETED: 'POLICY_DELETED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  EXPENSE_SUBMITTED: 'EXPENSE_SUBMITTED',
  EXPENSE_REVISED: 'EXPENSE_REVISED',
  ADMIN_OVERRIDE: 'ADMIN_OVERRIDE',
}

export const REFERENCE_TYPE = {
  EXPENSE: 'expense',
}